apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ovn-bgp-agent
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - frrk8s.metallb.io
  resources:
  - frrconfigurations
  verbs:
  - list
  - get
  - watch
  - create
  - update
  - delete
  - patch
