name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  chart-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v4.2.0
      - uses: actions/setup-python@v5.3.0
      - uses: helm/chart-testing-action@v2.7.0
      - run: ct lint --chart-dirs . --check-version-increment=false --target-branch ${{ github.event.repository.default_branch }}
